### ISSUE TITLE
new step required on RTD for webhook integration

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/documentation#1]
the exercises in episode 4 (deploying sphinx documentation to read the docs) doesn't work for me with existing instructions. 
However, the instructions on http://docs.readthedocs.io/en/latest/webhooks.html work. This requires the "Payload URL" on GitHub to be the URL of the integration on read the docs (and not http://readthedocs.org/build/user-doc-example) as in this lesson

**Comment by bast** [comment]
OK this then probably changed. It still worked in Copenhagen but is based on very old instructions. Please feel free to update.
