### ISSUE TITLE
Build HTML pages locally - inform the change directory 

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/documentation#106]
Current text:
Inside the cloned repository, run sphinx-build . _build

May be explicitly say 
Inside the cloned repository, cd into docs directory and then ....
Or 
Inside the cloned repository, run sphinx-build doc _build

**Comment by bast** [comment]
I think this issue is not relevant anymore. The text now recommends to do:
```
$ sphinx-build doc _build
```

Which IMO is better than building inside `doc/`.
