### ISSUE TITLE
Feedback from CodeRefinery/INES hackathon

### ISSUE THREAD

**Issue by annefou** [coderefinery/documentation#134]
- When deploying source documentation to readthedoc, we could add an example on how to add requirements.txt (or conda environment). Attendees got stuck with bibtex (deployment was failing as it requires some additional python packages).

**Comment by bast** [comment]
Do you have some example project that uses this? Just to see which packages exactly are needed. Then I can bake it into some exercise.

**Comment by annefou** [comment]
https://github.com/NorESMhub/NorESM/tree/master/doc

**Comment by annefou** [comment]
I can make a short example.

**Comment by bast** [comment]
Closing. This was a good point but is now less relevant since that episode has been re-focused away from RTD towards GH Actions.
