### ISSUE TITLE
Is sphinx_rtd_theme used?

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#151]
We check whether it's present, it is part of install instructions, but are we using it in the lesson?

**Comment by svenvanderburg** [comment]
Yes, in [episode 4 exercise 1](https://github.com/coderefinery/documentation/blob/gh-pages/_episodes/04-sphinx.md#exercise-1-generate-the-basic-documentation-template)

**Comment by bast** [comment]
It seems we can make this optional and perhaps should not verify it at the beginning of the lesson. But rather show that the looks can be changed and how to install it if it is not present.

**Comment by svenvanderburg** [comment]
I agree, when teaching this I also did not install it on purpose, then to quickly show how use `pip install`.

**Comment by annajiat** [comment]
If I remember correctly, 
"sphinx-build doc _build" probably failed in Git Bash on Windows during the workshop today
and it required "pip install sphinx_rtd_theme"
and then "sphinx-build doc _build" again
We need to test this in multiple environments.

**Comment by bast** [comment]
Indeed we are using it and now our install environment contains it.
