### ISSUE TITLE
How do I serve this lesson locally?

### ISSUE THREAD

**Issue by svenvanderburg** [coderefinery/documentation#158]
From other carpentry-style lessons I am used to serving the lesson locally using `make serve`, but there is no Makefile. I also cannot find instructions on how to serve this lesson?

I now worked around this by actually cloning the [jekyl-common](https://github.com/coderefinery/jekyll-common/tree/4fb9b5fa455ffef2e6d916eac390b9e2fa32e4a8) git submodule into my local clone of the lesson, then running `jekyll serve` which works, but it is not super contributer friendly.

**Comment by bast** [comment]
Good point and sorry for not making this clearer. We are now also considering to migrating this lesson to Sphinx which will make it easier to serve locally.

**Comment by bast** [comment]
Until we do that this is how I do it:
- `git clone recursive` the repo
- then I use this https://github.com/Starefossen/docker-github-pages

**Comment by bast** [comment]
The lesson now changed to Sphinx but still it will be useful to document how to build it. I will now add this information.

**Comment by bast** [comment]
I will soon send a PR but this is how I build it locally:
```
python -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
sphinx-build content _build
```

**Comment by rkdarst** [comment]
sphinx-lesson docs has a "contributing-to-a-lesson" page now that can
be linked to / where this can be added:

https://coderefinery.github.io/sphinx-lesson/contributing-to-a-lesson/
