### ISSUE TITLE
color blind friendly palette

### ISSUE THREAD

**Issue by annajiat** [coderefinery/documentation#161]
We might wish to review all the illustrations to ensure use of color blind friendly palette.

**References:**
- https://www.tableau.com/about/blog/examining-data-viz-rules-dont-use-red-green-together
- https://venngage.com/blog/color-blind-friendly-palette/
- https://davidmathlogic.com/colorblind/

**Comment by bast** [comment]
Good point. It seems the only illustration is this one: https://coderefinery.github.io/documentation/gh-pages/

And we have been discussing that to improve accessibility we could try expressing this in text rather than in an image.

**Comment by samumantha** [comment]
the github pages image has important colors chosen according to color blind friendly palette

**Comment by samumantha** [comment]
It is very good to keep this in mind for all lessons, but in this lesson this issue can be closed?

**Comment by bast** [comment]
I am closing this issue as resolved. Thanks again for raising it! The page in question is still not accessible enough but not because of colors but because it requires being able to see an image. I will try to convert it to be also understandable in text.
