### ISSUE TITLE
Maybe teach Markdown+Sphinx instead of RST+Sphinx?

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#202]
Suggestion came up in #200.

**Comment by bast** [comment]
This would require also using/showing https://myst-parser.readthedocs.io/.

**Comment by bast** [comment]
- Install instructions might need MyST
- Sphinx quickstart or conf.py setup might need to be changed

**Comment by samumantha** [comment]
Lesson rewritten to do just that. All now markdown, except for index.rst. Do not know if there is a markdown solution for that?

**Comment by rkdarst** [comment]
markdown, no; MyST, yes (insert my standard rambling here).  MyST
equivalent of the toctree directive, I guess you can infer it from
what you taught.

**Comment by rantahar** [comment]
I think sphinx-quickstart always generates an index.rst and replacing it would be an extra step. So I would keep index.rst, the modifications we make are simple enough that we don't need to get into RST.

**Comment by rantahar** [comment]
I suppose close this one, since we did do this in the previous workshop. Any improvements should already be in subsequent issues.
