### ISSUE TITLE
Copying code from Sphinx exercise is wrong 🐛

### ISSUE THREAD

**Issue by matuskalas** [coderefinery/documentation#204]
In https://coderefinery.github.io/documentation/sphinx/#group-exercise-build-sphinx-documentation-using-rst
(file **content/sphinx.md**)

I added the follwoing note also directly into https://github.com/coderefinery/documentation/commit/81b4b7e84e506dfc812ca92695e6c3538d590abf#r51014089:

Lines 32-36:

The copy button copies the whole content of _e.g._
```console
$ python --version

Python 3.7.0
```

including the '$' and the output, which is less than useful and can rather be confusing because it won't work and may not be clear why.

This applies to all code snippets here.

**Comment by bast** [comment]
As a note: we can use "```console"

**Comment by rantahar** [comment]
Changed this to console in a PR long time ago.
