### ISSUE TITLE
add example workflow 

### ISSUE THREAD

**Issue by samumantha** [coderefinery/documentation#205]
In may workshop we forgot to mention that it is good to make documentation changeable.

So for example we start a project, and think it will be only small so we start with a readme, then it grows and we might need to switch to sphinx or other tools and deploy it to readthedocs. This will be easy when sticking eg from the beginning to markdown and not mix stuff. 
Could be a sentence in the material about how is the workflow?

**Comment by bast** [comment]
This is a great point. Working on it ...
