### ISSUE TITLE
Update exercise naming for consistency

### ISSUE THREAD

**Issue by samumantha** [coderefinery/documentation#215]
Was it README-1, README-2,... and Sphinx-1,Sphinx-2,... that was the best naming convention?
Currently it is quite a mix

**Comment by bast** [comment]
https://coderefinery.org/sphinx-lesson/exercise-list/#recommendations-to-make-a-useful-list

**Comment by bast** [comment]
This was shared on Zulip but I did not have time to implement it myself. But it's a good recommendation.
