### ISSUE TITLE
Reference to literalinclude commented out

### ISSUE THREAD

**Issue by rantahar** [coderefinery/documentation#218]
It does not seem to work as implied in the text. Or at least I could not find a reference to the correct syntax.

**Comment by rantahar** [comment]
@rkdarst, do you know how `literalinclude` works in MyST? Does it?

**Comment by bast** [comment]
It works. Looking for an example ...

**Comment by bast** [comment]
Example: https://github.com/coderefinery/testing/blob/main/content/test-design.md?plain=1#L79
