### ISSUE TITLE
mathjax confusion

### ISSUE THREAD

**Issue by samumantha** [coderefinery/documentation#225]
from hackMD march 22:
115. I am a little bit confused with the latex extensions: I added the 'sphinx.ext.mathjax' which works fine. Then I followed the link you gave to the myst documentaion. There it says: "By adding "amsmath" to myst_enable_extensions (in the sphinx conf.py configuration file), you can enable direct parsing of amsmath LaTeX equations." I am not sure exactly how to do this. Anyway, even without adding the amsmath the latex "gather" enviornment worked. so, is the mathjax enough?
     - Mathjax is enough. 
     - I think mathjax is in Sphinx and works with any parser
     - The amsmath this is specific to myst-parser, and changes how it parses things.  So that it directly parses LaTeX, instead of needing to wrap it in the generic directives.
         - but how can we add the amsmath? like: myst_enable_extensions = ["amsmath"] ? so adding this line in conf file below the extensions = []...
         - Yes, I think like that in `conf.py`.  I haven't done this myself before.
         - - Seems to work. but I removed the mathjax extension

**Comment by rantahar** [comment]
Will keep this in mind when rereading.

**Comment by bast** [comment]
Solved in fa6d1ae7d09ca.
