### ISSUE TITLE
Say what to do if you are are using a default anaconda environment (myst-parser missing)

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/documentation#228]
While in theory everyone should install a dedicated coderefinery environment, many people didn't and the first sign of this was myst-parser missing.  Might be worth having a note on this error and how to fix. (note myst-parser is only in conda-forge)

**Comment by bast** [comment]
It is partially addressed but this should all move up where we test prerequisites.

**Comment by bast** [comment]
And while it would be nice to have a workaround for a vanilla Anaconda installation, I will simply assume that learners are running inside the `coderefinery` environment. It is too difficult to add workarounds inside lessons.
