### ISSUE TITLE
Is there a Sphinx project earlier in the workshop already?

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#252]
It seems somebody tried to make another project visible via Sphinx and GitHub Pages which was created earlier. This was similar but not the same and didn't work. Was that introduced in reproducible-research?

This could be aligned a bit better. We could have one project that we build up across the lessons. And we have tried that earlier already but also wanted to keep lessons modular. One thing that we should preserve is that learners can join late in the workshop and still be able to participate.

Good comment from @frankier.

**Comment by frankier** [comment]
It's [Sphinx-1](https://coderefinery.github.io/documentation/sphinx/#exercise-sphinx-basics) and [gh-pages-1](https://coderefinery.github.io/documentation/gh_workflow/#exercise-deploy-sphinx-documentation-to-github-pages). Looking now it's just a matter of adding `myst-parser`. Step 1 of gh-pages-1 could then mention that you can either clone the word-count template or continue to use the results of the previous section.

**Comment by bast** [comment]
I have now simplified and stream-lined all of this. This should not be an issue anymore.
