### ISSUE TITLE
the default GitHub will be read-only in the future (for new repos)

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/documentation#255]
The workflow file should request a rw token.

**Comment by bast** [comment]
I am looking into this ...

**Comment by bast** [comment]
@rkdarst do you mean the setting on pages like this one? https://github.com/coderefinery/documentation/settings/actions

(scroll to the end)

Or did you mean something else? Probably something else but I can't find an example although I remember that you/we changed something in few repos.

**Comment by rkdarst** [comment]
I've seen this added to yaml files:

```
    permissions:
      contents: write
```

https://github.com/peaceiris/actions-gh-pages/blob/main/README.md?plain=1#L154-L155

I'm not sure how this interacts with the settings page option.  I
would hope that only the yaml file would be sufficient, but it needs
testing.

**Comment by bast** [comment]
Closed by mistake.

**Comment by bast** [comment]
This seems to be already implemented.
