### ISSUE TITLE
I recommend to not use the word count example

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#256]
This couples this lesson to the reproducibility lesson: https://github.com/coderefinery/reproducible-research/issues/206

I think the coupling is unnecessary and harms more than it helps.

**Comment by bast** [comment]
Original motivation was to have continuity and let learners add documentation to a familiar example from an earlier lesson.

However, these are the downsides:
- some learners only join for a particular lesson and this is then not familiar
- word count example is very python-focused
- it contains files that are not relevant to documentation

I believe we can make a strong point with a simpler example.

**Comment by johanhellsvik** [comment]
Good idea. Changes has been implemented accordingly in https://github.com/coderefinery/documentation/pull/258 & https://github.com/coderefinery/documentation/commit/8a3edf065a276a7cd857f539e634126fb689866e .
