### ISSUE TITLE
Start with catchy example and collaborate on the beginning 

### ISSUE THREAD

**Issue by rlonka** [coderefinery/documentation#26]
Maybe use a more fleshy example to start with, working on documentation collaboratively (instead of everyone creating empty doc from scratch). Show what can be done.

**Comment by bast** [comment]
Would be fun but cannot introduce this for the upcoming workshop since we have this lesson on the first day. Once we move to a later day we can start from a real example and go collaboratively.

**Comment by bast** [comment]
Done in b1581099463cfa36e75cba957f62041f5826fe6f.
