### ISSUE TITLE
GitHub Pages: Deprecating the theme picker

### ISSUE THREAD

**Issue by zbynio414** [coderefinery/documentation#263]
Reference to:
[#content/gh-pages.md](https://github.com/coderefinery/documentation/blob/feb3e6c5e620aa050393f9a8dafee2d00e5c392b/content/gh-pages.md)

It seems that the instruction on page [https://pages.github.com/](https://pages.github.com/) is outdated with the "Choose a theme" section.

Section 'Theme chooser' is not visible in 'Setting/Pages'.

According to the GitHub Blog the functionality is depreciated.
[GitHub Pages: Deprecating the theme picker](https://github.blog/changelog/2022-08-22-github-pages-deprecating-the-theme-picker/)

More up-to-date instruction to create GitHub Page I've found under:
[https://docs.github.com/en/pages/quickstart](https://docs.github.com/en/pages/quickstart)

**Comment by bast** [comment]
Thanks for reporting!
