### ISSUE TITLE
Add instructions to generate Sphinx autodoc

### ISSUE THREAD

**Issue by luisaforozco** [coderefinery/documentation#267]
For python, sphinx has the [autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) module that generates a documentation of the members (functions, classes) based on their docstrings. I think this could be added as an Exercise at [Sphinx and Markdown](https://coderefinery.github.io/documentation/sphinx/).

In a lesson we included this and it was nice to show how your docstrings are rendered in the documentation. I could do this modification with the extra instructions that I used when we though it.

**Comment by bast** [comment]
This is a great suggestion and such addition would be most welcome. Please let me know if I can help with this somehow.

**Comment by luisaforozco** [comment]
Great, then I will start working on this and I will let you know if I find any issues.

**Comment by samumantha** [comment]
Any reason to keep this issue open? Looks wonderfully resolved to me :) - Thanks Luisa

**Comment by luisaforozco** [comment]
Yes, I will close it 👍
