### ISSUE TITLE
Maybe we can show some README.md tricks for GitHub?

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#274]
From https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts:

> [!NOTE]
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]
> Crucial information necessary for users to succeed.

> [!WARNING]
> Critical content demanding immediate user attention due to potential risks.

And another nice one:

<details>
<summary>
Short summary
</summary>

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</details>

**Comment by bast** [comment]
@samumantha do you think this is useful to add? Then I can add.

**Comment by samumantha** [comment]
I did not know about these! Yes, super useful! Please add

**Comment by samumantha** [comment]
Could also have something about badges on top of READMEs?
Many repositories have some, so some may wonder why and how

**Comment by bast** [comment]
Yes! Maybe we can add an exercise which contains some of these features and learners can have some fun adapting those.
