### ISSUE TITLE
change "ERROR: temperature is too low" to "ERROR: temperature is too high"

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#288]
This was not meant to be a subtle bug. This is a mistake in the lesson.

**Comment by bast** [comment]
And adjust comment. In other words: Comment B is supposed to show why something is done. It is meant to be the better comment and it is not meant to be subtly confusing.

**Comment by yelizy** [comment]
Actually, what is wrong in that part is not the comment but the direction of the sign. Measured temperature should not be lower than -50. It needs to be change to the 'Less-than sign'.

  **Comment A**
  ```python
  # now we check if temperature is larger than -50
  if temperature < -50:
      print("ERROR: temperature is too low")
  ```

  **Comment B**
  ```python
  # we regard temperatures below -50 degrees as measurement errors
  if temperature < -50:
      print("ERROR: temperature is too low")
  ```
  ```

**Comment by bast** [comment]
Good point. But in this case we should adjust the comment in Comment A. Unless we want it to be wrong. But this was not the goal.
