### ISSUE TITLE
show how to make your software citable

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/documentation#44]
A good option is using Zenodo with GitHub:
https://guides.github.com/activities/citable-code/

but maybe this fits better in the reproducibility lesson?

**Comment by bast** [comment]
I think here it can be a link or a mention but I agree that we can discuss more in detail in the reproducibility lesson.

**Comment by bast** [comment]
It's good if we plug it in somewhere in passing to remind participants and to re-connect to other lessons.

**Comment by wikfeldt** [comment]
this is covered now in the reproducibility lesson (b5c05c5fa379f3001c5c9669509551ca768aff02)
resolving
