### ISSUE TITLE
consider moving exercise instructions from example documentation to lesson material

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/documentation#49]
i.e. move the exercises from here:
https://github.com/coderefinery/word-count/blob/master/doc/exercises.rst

to here:
https://github.com/coderefinery/documentation/blob/gh-pages/_episodes/04-sphinx-rtd.md

it might be confusing to have the material spread over two webpages

**Comment by bast** [comment]
I agree we also have to think about how to make the exercises repeatable for future workshops.
