### ISSUE TITLE
For the GitHub pages example consider using the GitHub importer

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#53]
https://github.com/new/import

The advantage would be a repository that is not forked from upstream (because the fork relation then is unnecessary) and that is built right away and does not require a change to show up at all.

**Comment by bast** [comment]
Juho used this in Stockholm and indeed this looks like a better solution than forking.

**Comment by juholehtonen** [comment]
This was tested 27.3. Stockholm workshop and went fine. So we'll use the importer. I'll update the lesson accordingly.

**Comment by juholehtonen** [comment]
Fixed with pull request #98
