### ISSUE TITLE
Missing navigation options in lesson template

### ISSUE THREAD

**Issue by tiagopereira** [coderefinery/documentation#54]
It appears that all coderefinery lesson pages are missing some navigation links (next, previous). This is not exclusive for the documentation lesson. The template is very similar to the Software Carpentry template, but is missing this crucial bit. This makes it cumbersome when going into a lesson chapter page (e.g. https://coderefinery.github.io/documentation/02-requirements/) because one needs to go back to the contents list to navigate to the next chapter. Unless I'm missing something!

**Comment by bast** [comment]
Tiago, thank you! Very good suggestion.

**Comment by bast** [comment]
This needs to be fixed in https://github.com/coderefinery/jekyll-common/issues/3

**Comment by bast** [comment]
This has been fixed.
