### ISSUE TITLE
For the GH pages example consider using jekyll-theme-minimal

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#56]
As in this project: https://github.com/uit-no/python-open-mike/blob/gh-pages/_config.yml

Is simpler and IMO looks better.

**Comment by annefou** [comment]
I have tried but I am not sure it is any simpler.

**Comment by bast** [comment]
It is OK for me if we close this or postpone this. But can you please elaborate why this is not simpler? Or perhaps I should motivate why it would be simpler :-)

My argument for simpler:
- less stuff in `_config.yml`
- less stuff/clutter on the pages to think about where it came from

**Comment by annefou** [comment]
Ok I made a change and created a pull request but I don't have access to the repo so I cannot review/assign review and merge.

Could you have a look and merge if it is OK?

**Comment by annefou** [comment]
https://github.com/coderefinery/gh-pages-example

**Comment by bast** [comment]
Thank you. Also I now gave CodeRefinery staff write perms to the repo.

**Comment by bast** [comment]
The change is merged - can we close this?

**Comment by annefou** [comment]
yes. Thanks!

**Comment by bast** [comment]
Thank you for the work!
