### ISSUE TITLE
Use the same project created to host on Readthedocs not a new one

### ISSUE THREAD

**Issue by Sabryr** [coderefinery/documentation#63]
See whether we can use the example project created in 
Sphinx and ReStructuredText | How do we get started on writing Sphinx documentation in RST?
in 
Deploying Sphinx documentation to Read the Docs

instead of cloning a completely new project

**Comment by bast** [comment]
Related to #66.

**Comment by bast** [comment]
I can work on it but love to get some feedback from the team first to avoid that I spend time on such a change and later it gets rejected.

**Comment by bast** [comment]
Conclusion from #66 seems that we keep the word-count example.
