### ISSUE TITLE
Move GitHub pages part to collaborative Git lesson

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#64]

**Comment by annefou** [comment]
@bast Could you clarify this issue? I don't fully understand what you expect here? Thanks.

**Comment by bast** [comment]
I don't think this was my idea so I am only the messenger. But at some point somebody (you?) suggested that we could create a GitHub pages as a collaborative project during collaborative Git and take it out of the documentation lesson. I am not 100% sure about this but I noted this here so that we would not forget.

**Comment by annefou** [comment]
Yes! Ok. Now I remember... Good that you added this issue (I forgot completely!).

**Comment by bast** [comment]
This issue is here since a year and we haven't done it. Perhaps this means we should not do it. It would be a nice application to collaborative Git but would require us to add content to an already long lesson. And although it is quite a context jump from Read the Docs to GitHub pages, I think it fits here.

Closing but please reopen if you think that we should follow up on this.
