### ISSUE TITLE
Add documentation from scratch to the word-count project

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#66]
~Mention with a link how to run your own sphinx server for those who do not want to deploy to RTD and not pay.~

**Comment by bast** [comment]
This project has been forked and cloned earlier in the workshop in the reproducibility lesson.

This will avoid changing context between sphinx-quickstart and deploying it to RTD.

**Comment by bast** [comment]
Seems related to #63.

**Comment by bast** [comment]
What I like about the word count example here: it is better than a hello world.
But what I don't like so much: it assumes that participants have seen it before. In other words it couples lessons which could be more decoupled.

I know and remember that our attempt was to have a "story" that goes through all lessons but one downside of one story is that it couples lessons and enforces a certain order to them. It can make the lesson less reusable on its own outside of a CodeRefinery workshop.

I am unsure now what is better but just noting my thoughts.

**Comment by rkdarst** [comment]
I think that "long story" and "modular" are two matters that are both important, and we just have to do a delicate balance to make both possible.  But overall, the benefit of making it a continuous story is worth it.

In this case, though, is it too hard to have a "clone this repository" instruction and also "if you already have this cloned, then go back there" somehow?  I'm sure we can make it work, documentation shouldn't have to depend on doing that much else in the repo... I think.

**Comment by bast** [comment]
Thanks for feedback!

**Comment by bast** [comment]
I will add such a box. Good idea.

In Git intro the word count felt much more artificial for me: https://github.com/coderefinery/git-intro/issues/181

But here I will make it work somehow.

**Comment by wikfeldt** [comment]
I agree that word-count looks artifical in git-intro. I'll do something about that

**Comment by bast** [comment]
Concluding that word-count is good here. Keeping things as they are. I think it will work fine.
