### ISSUE TITLE
Document how to rewind the word-count central example

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#76]
I will do that and document how to do it so that we start from a "clean" repo but also we want to keep previous contributions.

**Comment by wikfeldt** [comment]
For Uppsala I both tagged the last commit from the Reykjavik workshop and also squashed all the participant commits to a new branch reykjavik-aug-2018

**Comment by bast** [comment]
The tag preserves the commits. I think we should do either or but perhaps not both. Which one do we prefer? Or really both?

**Comment by bast** [comment]
I agree - I will do that.

**Comment by bast** [comment]
I am just doing the cleanup. One possible problem is that the closed PRs survive. So we might want to do the exercise on a mirror of the Git repository and then we nuke it after the workshop - similarly to Git collaborative. The downside of that is that it will probably dissociate RTD which we would have to re-enable every time.
