### ISSUE TITLE
Mention with a link how to run your own sphinx server

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#79]
Mention with a link how to run your own sphinx server for those who do not want to deploy to RTD and not pay.

**Comment by blankdots** [comment]
I think the simplest way would be to run a simple web server e.g.:
```
cd _build/html
python -m http.server 8080
```
Or you were thinking something along the lines of: 
* https://docs.readthedocs.io/en/latest/install.html
* https://pypi.org/project/sphinx-autobuild/
* https://pypi.org/project/sphinx-server/

**Comment by bast** [comment]
Yes I think we can mention this with links and 1-2 sentences in the talk.

I was also thinking that we could mention that it is possible to run sphinx as part of CI/CD and to deploy the documentation to GitHub/GitLab pages.

**Comment by Sabryr** [comment]
I am pessimistic about running own web-server (uptime, ports, security, load....), when there free solutions that you can use.

**Comment by bast** [comment]
We can link that this is possible. I would personally always recommend to not run own servers.

**Comment by blankdots** [comment]
We can mention in the documentation, but when doing the workshop I would first ask the participants if they want this information. 

I remember in Aalto Workshop i asked if anyone is interested what happens behind Github pages with Jekyll and what happens behind read the docs, and I have got no interested in that information. 

I assume it is enough for most people to work with readthedocs.org and https://pages.github.com/ ... but for those that want to set it up in their internal network (i assume some have internal servers at their disposal) I think this is useful information.
