### ISSUE TITLE
Create super simple infographics for GH pages

### ISSUE THREAD

**Issue by bast** [coderefinery/documentation#85]
I will doodle a draft - now just a reminder for me to not forget. I think this will help us to condense 2 paragraphs into one graphics.

**Comment by bast** [comment]
I would like to use this which would replace some of the text:
![gh-pages](https://user-images.githubusercontent.com/5120679/55168578-5921ff80-5173-11e9-8bf0-997da3e9b6d7.jpg)

**Comment by wikfeldt** [comment]
looks really good, good idea to add this

**Comment by bast** [comment]
OK I will send a PR with that addition.
